import type { Location, DashboardData, ForecastData, ForecastPoint, Hotspot, AdvisoryData } from "@/types";

// ===== Indian Cities with Real Coordinates =====
export const mockLocations: Location[] = [
  {
    id: "loc-01", city: "Delhi", state: "Delhi", ward: "Anand Vihar",
    latitude: 28.6139, longitude: 77.2090, currentAqi: 312, forecastAqi: 290,
    temperature: 38, humidity: 45, windSpeed: 8, rainfall: 0,
    dominantPollutant: "PM2.5", confidenceScore: 92, priorityLevel: "Emergency",
    recommendation: "Declare air emergency. Deploy anti-smog guns. Restrict construction.",
    pollutants: { pm25: 185, pm10: 290, no2: 68, co: 4.2, so2: 22, o3: 45 },
    nearbyRoads: 12, nearbySchools: 8, nearbyHospitals: 3, nearbyIndustries: 5,
    nearbyConstructionSites: 7, greenCoverPercent: 12,
    healthRisk: "Severe",
    sources: { traffic: 35, industry: 20, construction: 18, cropBurning: 15, fire: 5, dust: 7 },
  },
  {
    id: "loc-02", city: "Mumbai", state: "Maharashtra", ward: "Bandra",
    latitude: 19.0760, longitude: 72.8777, currentAqi: 142, forecastAqi: 155,
    temperature: 32, humidity: 78, windSpeed: 14, rainfall: 2,
    dominantPollutant: "PM10", confidenceScore: 88, priorityLevel: "Alert",
    recommendation: "Issue health advisory for sensitive groups. Monitor coastal wind patterns.",
    pollutants: { pm25: 72, pm10: 145, no2: 52, co: 2.8, so2: 18, o3: 35 },
    nearbyRoads: 9, nearbySchools: 6, nearbyHospitals: 4, nearbyIndustries: 3,
    nearbyConstructionSites: 5, greenCoverPercent: 18,
    healthRisk: "High",
    sources: { traffic: 40, industry: 15, construction: 20, cropBurning: 0, fire: 5, dust: 20 },
  },
  {
    id: "loc-03", city: "Bangalore", state: "Karnataka", ward: "Whitefield",
    latitude: 12.9716, longitude: 77.5946, currentAqi: 78, forecastAqi: 85,
    temperature: 28, humidity: 65, windSpeed: 10, rainfall: 5,
    dominantPollutant: "NO2", confidenceScore: 91, priorityLevel: "Watch",
    recommendation: "Continue monitoring. Traffic management at IT corridors recommended.",
    pollutants: { pm25: 38, pm10: 72, no2: 48, co: 1.9, so2: 12, o3: 42 },
    nearbyRoads: 7, nearbySchools: 5, nearbyHospitals: 3, nearbyIndustries: 2,
    nearbyConstructionSites: 8, greenCoverPercent: 28,
    healthRisk: "Moderate",
    sources: { traffic: 50, industry: 10, construction: 25, cropBurning: 0, fire: 2, dust: 13 },
  },
  {
    id: "loc-04", city: "Kolkata", state: "West Bengal", ward: "Jadavpur",
    latitude: 22.5726, longitude: 88.3639, currentAqi: 198, forecastAqi: 210,
    temperature: 35, humidity: 82, windSpeed: 6, rainfall: 0,
    dominantPollutant: "PM2.5", confidenceScore: 85, priorityLevel: "Alert",
    recommendation: "Advisory for outdoor workers. Increase water sprinkling on roads.",
    pollutants: { pm25: 110, pm10: 180, no2: 58, co: 3.5, so2: 25, o3: 38 },
    nearbyRoads: 10, nearbySchools: 7, nearbyHospitals: 2, nearbyIndustries: 6,
    nearbyConstructionSites: 4, greenCoverPercent: 15,
    healthRisk: "High",
    sources: { traffic: 30, industry: 25, construction: 15, cropBurning: 10, fire: 8, dust: 12 },
  },
  {
    id: "loc-05", city: "Chennai", state: "Tamil Nadu", ward: "T. Nagar",
    latitude: 13.0827, longitude: 80.2707, currentAqi: 95, forecastAqi: 88,
    temperature: 34, humidity: 72, windSpeed: 12, rainfall: 0,
    dominantPollutant: "PM10", confidenceScore: 87, priorityLevel: "Watch",
    recommendation: "Monitor industrial zones. Enforce emission norms in Manali area.",
    pollutants: { pm25: 48, pm10: 92, no2: 42, co: 2.1, so2: 15, o3: 50 },
    nearbyRoads: 8, nearbySchools: 4, nearbyHospitals: 3, nearbyIndustries: 4,
    nearbyConstructionSites: 3, greenCoverPercent: 22,
    healthRisk: "Moderate",
    sources: { traffic: 35, industry: 25, construction: 10, cropBurning: 5, fire: 5, dust: 20 },
  },
  {
    id: "loc-06", city: "Hyderabad", state: "Telangana", ward: "HITEC City",
    latitude: 17.3850, longitude: 78.4867, currentAqi: 68, forecastAqi: 72,
    temperature: 30, humidity: 60, windSpeed: 11, rainfall: 8,
    dominantPollutant: "NO2", confidenceScore: 90, priorityLevel: "Normal",
    recommendation: "Air quality satisfactory. Continue routine monitoring.",
    pollutants: { pm25: 32, pm10: 65, no2: 44, co: 1.5, so2: 10, o3: 38 },
    nearbyRoads: 6, nearbySchools: 5, nearbyHospitals: 4, nearbyIndustries: 2,
    nearbyConstructionSites: 6, greenCoverPercent: 30,
    healthRisk: "Moderate",
    sources: { traffic: 45, industry: 12, construction: 22, cropBurning: 0, fire: 3, dust: 18 },
  },
  {
    id: "loc-07", city: "Ahmedabad", state: "Gujarat", ward: "Satellite",
    latitude: 23.0225, longitude: 72.5714, currentAqi: 175, forecastAqi: 168,
    temperature: 40, humidity: 35, windSpeed: 9, rainfall: 0,
    dominantPollutant: "PM10", confidenceScore: 86, priorityLevel: "Alert",
    recommendation: "Dust suppression measures needed. Monitor industrial emissions.",
    pollutants: { pm25: 88, pm10: 165, no2: 55, co: 3.0, so2: 20, o3: 42 },
    nearbyRoads: 8, nearbySchools: 5, nearbyHospitals: 2, nearbyIndustries: 7,
    nearbyConstructionSites: 4, greenCoverPercent: 14,
    healthRisk: "High",
    sources: { traffic: 25, industry: 30, construction: 15, cropBurning: 5, fire: 5, dust: 20 },
  },
  {
    id: "loc-08", city: "Pune", state: "Maharashtra", ward: "Hinjewadi",
    latitude: 18.5204, longitude: 73.8567, currentAqi: 82, forecastAqi: 90,
    temperature: 29, humidity: 68, windSpeed: 10, rainfall: 3,
    dominantPollutant: "PM2.5", confidenceScore: 89, priorityLevel: "Watch",
    recommendation: "Monitor IT park area traffic congestion. Promote public transport.",
    pollutants: { pm25: 42, pm10: 78, no2: 40, co: 1.8, so2: 11, o3: 44 },
    nearbyRoads: 6, nearbySchools: 4, nearbyHospitals: 3, nearbyIndustries: 3,
    nearbyConstructionSites: 5, greenCoverPercent: 25,
    healthRisk: "Moderate",
    sources: { traffic: 42, industry: 15, construction: 20, cropBurning: 0, fire: 3, dust: 20 },
  },
  {
    id: "loc-09", city: "Jaipur", state: "Rajasthan", ward: "C-Scheme",
    latitude: 26.9124, longitude: 75.7873, currentAqi: 155, forecastAqi: 162,
    temperature: 42, humidity: 25, windSpeed: 15, rainfall: 0,
    dominantPollutant: "PM10", confidenceScore: 84, priorityLevel: "Alert",
    recommendation: "Dust storms expected. Issue public advisory. Close open windows.",
    pollutants: { pm25: 78, pm10: 155, no2: 45, co: 2.4, so2: 14, o3: 55 },
    nearbyRoads: 7, nearbySchools: 5, nearbyHospitals: 2, nearbyIndustries: 3,
    nearbyConstructionSites: 6, greenCoverPercent: 10,
    healthRisk: "High",
    sources: { traffic: 20, industry: 15, construction: 12, cropBurning: 3, fire: 5, dust: 45 },
  },
  {
    id: "loc-10", city: "Lucknow", state: "Uttar Pradesh", ward: "Gomti Nagar",
    latitude: 26.8467, longitude: 80.9462, currentAqi: 245, forecastAqi: 230,
    temperature: 36, humidity: 55, windSpeed: 5, rainfall: 0,
    dominantPollutant: "PM2.5", confidenceScore: 88, priorityLevel: "Critical",
    recommendation: "Restrict vehicular movement. Deploy fog cannons. Close schools.",
    pollutants: { pm25: 140, pm10: 225, no2: 62, co: 3.8, so2: 28, o3: 40 },
    nearbyRoads: 9, nearbySchools: 6, nearbyHospitals: 2, nearbyIndustries: 4,
    nearbyConstructionSites: 5, greenCoverPercent: 13,
    healthRisk: "Very High",
    sources: { traffic: 30, industry: 22, construction: 18, cropBurning: 15, fire: 5, dust: 10 },
  },
  {
    id: "loc-11", city: "Kanpur", state: "Uttar Pradesh", ward: "Fazalganj",
    latitude: 26.4499, longitude: 80.3319, currentAqi: 278, forecastAqi: 265,
    temperature: 37, humidity: 50, windSpeed: 4, rainfall: 0,
    dominantPollutant: "PM2.5", confidenceScore: 83, priorityLevel: "Critical",
    recommendation: "Industrial shutdown advisory. Emergency health camps. Mask distribution.",
    pollutants: { pm25: 158, pm10: 255, no2: 70, co: 4.0, so2: 32, o3: 35 },
    nearbyRoads: 11, nearbySchools: 7, nearbyHospitals: 1, nearbyIndustries: 8,
    nearbyConstructionSites: 3, greenCoverPercent: 8,
    healthRisk: "Very High",
    sources: { traffic: 25, industry: 35, construction: 12, cropBurning: 12, fire: 6, dust: 10 },
  },
  {
    id: "loc-12", city: "Chandigarh", state: "Chandigarh",
    latitude: 30.7333, longitude: 76.7794, currentAqi: 125, forecastAqi: 135,
    temperature: 33, humidity: 52, windSpeed: 8, rainfall: 0,
    dominantPollutant: "PM2.5", confidenceScore: 90, priorityLevel: "Alert",
    recommendation: "Seasonal stubble burning impact. Coordinate with Punjab/Haryana authorities.",
    pollutants: { pm25: 65, pm10: 120, no2: 48, co: 2.5, so2: 16, o3: 40 },
    nearbyRoads: 5, nearbySchools: 4, nearbyHospitals: 3, nearbyIndustries: 1,
    nearbyConstructionSites: 3, greenCoverPercent: 35,
    healthRisk: "High",
    sources: { traffic: 25, industry: 10, construction: 10, cropBurning: 40, fire: 5, dust: 10 },
  },
  {
    id: "loc-13", city: "Bhopal", state: "Madhya Pradesh", ward: "New Market",
    latitude: 23.2599, longitude: 77.4126, currentAqi: 105, forecastAqi: 112,
    temperature: 35, humidity: 48, windSpeed: 7, rainfall: 0,
    dominantPollutant: "PM10", confidenceScore: 86, priorityLevel: "Watch",
    recommendation: "Monitor lake-area industrial zone. Enforce vehicular emission checks.",
    pollutants: { pm25: 55, pm10: 100, no2: 42, co: 2.2, so2: 14, o3: 38 },
    nearbyRoads: 6, nearbySchools: 4, nearbyHospitals: 2, nearbyIndustries: 3,
    nearbyConstructionSites: 4, greenCoverPercent: 24,
    healthRisk: "Moderate",
    sources: { traffic: 30, industry: 22, construction: 15, cropBurning: 8, fire: 5, dust: 20 },
  },
  {
    id: "loc-14", city: "Patna", state: "Bihar", ward: "Boring Road",
    latitude: 25.6093, longitude: 85.1376, currentAqi: 220, forecastAqi: 235,
    temperature: 36, humidity: 62, windSpeed: 5, rainfall: 0,
    dominantPollutant: "PM2.5", confidenceScore: 82, priorityLevel: "Critical",
    recommendation: "Ban firecrackers. Deploy mobile monitoring units. Emergency advisory.",
    pollutants: { pm25: 128, pm10: 205, no2: 58, co: 3.6, so2: 24, o3: 36 },
    nearbyRoads: 8, nearbySchools: 6, nearbyHospitals: 2, nearbyIndustries: 4,
    nearbyConstructionSites: 5, greenCoverPercent: 11,
    healthRisk: "Very High",
    sources: { traffic: 28, industry: 20, construction: 15, cropBurning: 20, fire: 7, dust: 10 },
  },
  {
    id: "loc-15", city: "Guwahati", state: "Assam", ward: "Paltan Bazaar",
    latitude: 26.1445, longitude: 91.7362, currentAqi: 55, forecastAqi: 60,
    temperature: 30, humidity: 80, windSpeed: 8, rainfall: 12,
    dominantPollutant: "PM10", confidenceScore: 88, priorityLevel: "Normal",
    recommendation: "Air quality good. Maintain green cover initiatives.",
    pollutants: { pm25: 25, pm10: 52, no2: 30, co: 1.2, so2: 8, o3: 30 },
    nearbyRoads: 4, nearbySchools: 3, nearbyHospitals: 2, nearbyIndustries: 1,
    nearbyConstructionSites: 2, greenCoverPercent: 42,
    healthRisk: "Low",
    sources: { traffic: 35, industry: 10, construction: 15, cropBurning: 5, fire: 10, dust: 25 },
  },
  {
    id: "loc-16", city: "Varanasi", state: "Uttar Pradesh", ward: "Assi Ghat",
    latitude: 25.3176, longitude: 82.9739, currentAqi: 195, forecastAqi: 188,
    temperature: 37, humidity: 58, windSpeed: 6, rainfall: 0,
    dominantPollutant: "PM2.5", confidenceScore: 85, priorityLevel: "Alert",
    recommendation: "Control cremation ground emissions. River bank dust suppression needed.",
    pollutants: { pm25: 105, pm10: 185, no2: 55, co: 3.2, so2: 20, o3: 42 },
    nearbyRoads: 7, nearbySchools: 5, nearbyHospitals: 2, nearbyIndustries: 3,
    nearbyConstructionSites: 4, greenCoverPercent: 14,
    healthRisk: "High",
    sources: { traffic: 25, industry: 18, construction: 12, cropBurning: 15, fire: 15, dust: 15 },
  },
  {
    id: "loc-17", city: "Visakhapatnam", state: "Andhra Pradesh", ward: "Beach Road",
    latitude: 17.6868, longitude: 83.2185, currentAqi: 72, forecastAqi: 68,
    temperature: 31, humidity: 75, windSpeed: 16, rainfall: 1,
    dominantPollutant: "PM10", confidenceScore: 91, priorityLevel: "Normal",
    recommendation: "Sea breeze favorable. Monitor steel plant emissions.",
    pollutants: { pm25: 35, pm10: 68, no2: 38, co: 1.6, so2: 12, o3: 45 },
    nearbyRoads: 5, nearbySchools: 3, nearbyHospitals: 3, nearbyIndustries: 2,
    nearbyConstructionSites: 3, greenCoverPercent: 28,
    healthRisk: "Moderate",
    sources: { traffic: 30, industry: 25, construction: 10, cropBurning: 0, fire: 5, dust: 30 },
  },
  {
    id: "loc-18", city: "Nagpur", state: "Maharashtra", ward: "Dharampeth",
    latitude: 21.1458, longitude: 79.0882, currentAqi: 110, forecastAqi: 118,
    temperature: 38, humidity: 42, windSpeed: 7, rainfall: 0,
    dominantPollutant: "PM10", confidenceScore: 87, priorityLevel: "Watch",
    recommendation: "Monitor MIHAN industrial zone. Increase green belt plantations.",
    pollutants: { pm25: 58, pm10: 108, no2: 45, co: 2.3, so2: 16, o3: 40 },
    nearbyRoads: 7, nearbySchools: 4, nearbyHospitals: 2, nearbyIndustries: 4,
    nearbyConstructionSites: 5, greenCoverPercent: 20,
    healthRisk: "Moderate",
    sources: { traffic: 30, industry: 25, construction: 18, cropBurning: 5, fire: 4, dust: 18 },
  },
  {
    id: "loc-19", city: "Coimbatore", state: "Tamil Nadu", ward: "RS Puram",
    latitude: 11.0168, longitude: 76.9558, currentAqi: 42, forecastAqi: 45,
    temperature: 27, humidity: 70, windSpeed: 12, rainfall: 6,
    dominantPollutant: "PM10", confidenceScore: 93, priorityLevel: "Normal",
    recommendation: "Air quality good. Excellent green cover. Model city for others.",
    pollutants: { pm25: 18, pm10: 40, no2: 25, co: 0.8, so2: 6, o3: 28 },
    nearbyRoads: 4, nearbySchools: 3, nearbyHospitals: 3, nearbyIndustries: 2,
    nearbyConstructionSites: 2, greenCoverPercent: 38,
    healthRisk: "Low",
    sources: { traffic: 35, industry: 15, construction: 12, cropBurning: 0, fire: 3, dust: 35 },
  },
  {
    id: "loc-20", city: "Ghaziabad", state: "Uttar Pradesh", ward: "Indirapuram",
    latitude: 28.6692, longitude: 77.4538, currentAqi: 335, forecastAqi: 310,
    temperature: 39, humidity: 42, windSpeed: 4, rainfall: 0,
    dominantPollutant: "PM2.5", confidenceScore: 90, priorityLevel: "Emergency",
    recommendation: "Lock down industrial zones. Deploy NDRF. Evacuate sensitive populations.",
    pollutants: { pm25: 200, pm10: 320, no2: 75, co: 4.8, so2: 35, o3: 48 },
    nearbyRoads: 14, nearbySchools: 9, nearbyHospitals: 2, nearbyIndustries: 8,
    nearbyConstructionSites: 10, greenCoverPercent: 6,
    healthRisk: "Severe",
    sources: { traffic: 30, industry: 28, construction: 22, cropBurning: 10, fire: 5, dust: 5 },
  },
];

// ===== Dashboard Data =====
export const mockDashboard: DashboardData = {
  currentAqi: 187,
  averageAqi: 156,
  highRiskAreas: 8,
  activeAlerts: 14,
  worstCity: "Ghaziabad",
  worstCityAqi: 335,
  monitoringStations: 234,
  trends: {
    currentAqiTrend: 5.2,
    averageAqiTrend: -2.8,
    highRiskTrend: 12.5,
    alertsTrend: 8.3,
  },
  sparklines: {
    currentAqi: [165, 172, 180, 175, 188, 192, 187],
    averageAqi: [162, 158, 160, 155, 152, 158, 156],
    highRisk: [5, 6, 5, 7, 6, 7, 8],
    alerts: [10, 8, 12, 11, 13, 12, 14],
  },
  recentAlerts: [
    { id: "a1", city: "Ghaziabad", state: "UP", message: "AQI crossed 300. Emergency protocols activated.", severity: "critical", timestamp: "2 min ago" },
    { id: "a2", city: "Delhi", state: "Delhi", message: "PM2.5 levels hazardous. Schools closure recommended.", severity: "danger", timestamp: "15 min ago" },
    { id: "a3", city: "Kanpur", state: "UP", message: "Industrial emissions spike detected in Fazalganj.", severity: "danger", timestamp: "32 min ago" },
    { id: "a4", city: "Lucknow", state: "UP", message: "AQI forecast worsening for next 48 hours.", severity: "warning", timestamp: "1 hr ago" },
    { id: "a5", city: "Patna", state: "Bihar", message: "Crop burning detected in surrounding districts.", severity: "warning", timestamp: "2 hr ago" },
    { id: "a6", city: "Jaipur", state: "Rajasthan", message: "Dust storm alert. PM10 levels rising rapidly.", severity: "warning", timestamp: "3 hr ago" },
  ],
};

// ===== Forecast Data =====
function generateHourlyForecast(baseAqi: number): ForecastPoint[] {
  const hours: ForecastPoint[] = [];
  for (let i = 0; i < 72; i++) {
    const variation = Math.sin(i / 6) * 30 + (Math.random() - 0.5) * 20;
    const aqi = Math.max(10, Math.round(baseAqi + variation));
    hours.push({
      time: `${i}h`,
      aqi,
      pm25: Math.round(aqi * 0.55),
      pm10: Math.round(aqi * 0.85),
      no2: Math.round(aqi * 0.25),
      co: +(aqi * 0.015).toFixed(1),
      so2: Math.round(aqi * 0.08),
    });
  }
  return hours;
}

export const mockForecast: ForecastData = {
  city: "Delhi",
  hourly: generateHourlyForecast(312),
  daily: [
    { time: "Mon", aqi: 295, pm25: 170, pm10: 265, no2: 65, co: 4.0, so2: 22 },
    { time: "Tue", aqi: 312, pm25: 185, pm10: 290, no2: 68, co: 4.2, so2: 24 },
    { time: "Wed", aqi: 290, pm25: 165, pm10: 260, no2: 62, co: 3.8, so2: 20 },
    { time: "Thu", aqi: 275, pm25: 155, pm10: 245, no2: 58, co: 3.5, so2: 19 },
    { time: "Fri", aqi: 260, pm25: 145, pm10: 230, no2: 55, co: 3.3, so2: 18 },
    { time: "Sat", aqi: 248, pm25: 138, pm10: 220, no2: 52, co: 3.1, so2: 17 },
    { time: "Sun", aqi: 235, pm25: 130, pm10: 210, no2: 50, co: 2.9, so2: 16 },
  ],
  weekly: [
    { time: "Week 1", aqi: 280, pm25: 160, pm10: 250, no2: 60, co: 3.7, so2: 21 },
    { time: "Week 2", aqi: 255, pm25: 142, pm10: 228, no2: 55, co: 3.3, so2: 18 },
    { time: "Week 3", aqi: 230, pm25: 125, pm10: 205, no2: 48, co: 2.8, so2: 16 },
    { time: "Week 4", aqi: 210, pm25: 112, pm10: 188, no2: 44, co: 2.5, so2: 14 },
  ],
};

// ===== Hotspot Data =====
export const mockHotspots: Hotspot[] = [
  { rank: 1, latitude: 28.6692, longitude: 77.4538, city: "Ghaziabad", state: "UP", aqi: 335, forecastAqi: 310, risk: "Severe", reason: "Industrial + vehicular + construction", action: "Emergency lockdown" },
  { rank: 2, latitude: 28.6139, longitude: 77.2090, city: "Delhi", state: "Delhi", aqi: 312, forecastAqi: 290, risk: "Severe", reason: "Vehicular + stubble burning", action: "Anti-smog guns deployed" },
  { rank: 3, latitude: 26.4499, longitude: 80.3319, city: "Kanpur", state: "UP", aqi: 278, forecastAqi: 265, risk: "Very High", reason: "Industrial emissions", action: "Factory shutdown advisory" },
  { rank: 4, latitude: 26.8467, longitude: 80.9462, city: "Lucknow", state: "UP", aqi: 245, forecastAqi: 230, risk: "Very High", reason: "Traffic + construction dust", action: "Restrict heavy vehicles" },
  { rank: 5, latitude: 25.6093, longitude: 85.1376, city: "Patna", state: "Bihar", aqi: 220, forecastAqi: 235, risk: "Very High", reason: "Crop burning + low wind", action: "Emergency health camps" },
  { rank: 6, latitude: 25.3176, longitude: 82.9739, city: "Varanasi", state: "UP", aqi: 195, forecastAqi: 188, risk: "High", reason: "Cremation + vehicular", action: "Monitor & advise" },
  { rank: 7, latitude: 22.5726, longitude: 88.3639, city: "Kolkata", state: "West Bengal", aqi: 198, forecastAqi: 210, risk: "High", reason: "Industrial + traffic", action: "Road water sprinkling" },
  { rank: 8, latitude: 23.0225, longitude: 72.5714, city: "Ahmedabad", state: "Gujarat", aqi: 175, forecastAqi: 168, risk: "High", reason: "Industrial + dust", action: "Dust suppression" },
  { rank: 9, latitude: 26.9124, longitude: 75.7873, city: "Jaipur", state: "Rajasthan", aqi: 155, forecastAqi: 162, risk: "High", reason: "Dust storms", action: "Public advisory" },
  { rank: 10, latitude: 19.0760, longitude: 72.8777, city: "Mumbai", state: "Maharashtra", aqi: 142, forecastAqi: 155, risk: "High", reason: "Construction + traffic", action: "Enforce emission norms" },
];

// ===== Advisory Data =====
export const mockAdvisory: AdvisoryData = {
  currentAqi: 187,
  healthRisk: "High",
  generalAdvice: "Air quality is unhealthy. Everyone may begin to experience health effects. Members of sensitive groups may experience more serious health effects.",
  recommendations: [
    { id: "r1", icon: "😷", category: "general", title: "Wear N95 Mask", description: "Everyone should wear N95 or equivalent masks when going outdoors. Cloth masks are NOT effective against PM2.5.", severity: "high" },
    { id: "r2", icon: "🏃", category: "outdoor", title: "Avoid Outdoor Exercise", description: "Postpone all outdoor physical activities. Move workouts indoors or to air-conditioned gyms.", severity: "high" },
    { id: "r3", icon: "🏫", category: "schools", title: "Schools: Suspend Outdoor Sports", description: "All schools should suspend outdoor sports activities and assemblies. Keep classroom windows closed.", severity: "high" },
    { id: "r4", icon: "👴", category: "elderly", title: "Elderly: Stay Indoors", description: "Senior citizens with respiratory or cardiac conditions should remain indoors. Use air purifiers if available.", severity: "critical" },
    { id: "r5", icon: "👶", category: "children", title: "Children: Avoid Prolonged Exposure", description: "Children under 12 should not spend more than 30 minutes outdoors. Monitor for coughing, sneezing, or breathing difficulty.", severity: "high" },
    { id: "r6", icon: "🏥", category: "medical", title: "Medical Preparedness", description: "Hospitals should increase capacity for respiratory emergencies. Stock up on bronchodilators and oxygen supplies.", severity: "moderate" },
    { id: "r7", icon: "🚗", category: "general", title: "Reduce Vehicle Use", description: "Use public transport or carpool. Avoid idling engines. Consider working from home if possible.", severity: "moderate" },
    { id: "r8", icon: "🪟", category: "general", title: "Keep Windows Closed", description: "Keep all windows and doors closed. Use air purifiers with HEPA filters. Seal gaps around windows.", severity: "high" },
  ],
};

// ===== Chat Suggested Questions =====
export const suggestedQuestions = [
  "Why has AQI increased in Delhi today?",
  "Which location needs immediate inspection?",
  "What caused the pollution spike in Ghaziabad?",
  "How can authorities reduce pollution in UP?",
  "What is the 72-hour forecast for Mumbai?",
  "Which pollutant is most dangerous right now?",
  "Recommend emergency actions for Kanpur",
  "Compare AQI trends across metro cities",
];

// ===== Mock Chat Responses =====
export const mockChatResponses: Record<string, string> = {
  default: "Based on my analysis of the current air quality data across India, I can see several concerning trends. The Indo-Gangetic Plain continues to show elevated pollution levels, particularly in UP and Bihar. Would you like me to drill down into a specific region or pollutant?",
  "why": "The AQI increase in Delhi is attributed to multiple converging factors:\n\n1. **Stubble Burning**: Satellite imagery shows active crop residue burning in Punjab and Haryana, contributing ~15% of Delhi's PM2.5.\n\n2. **Temperature Inversion**: A thermal inversion layer at ~500m is trapping pollutants near the surface.\n\n3. **Low Wind Speed**: Wind speeds dropped to 4-5 km/h, reducing natural dispersion.\n\n4. **Construction Activity**: 7 major construction sites operating without proper dust control.\n\n**Recommended Actions**: Deploy anti-smog guns in Anand Vihar, restrict construction between 6 AM - 10 AM, and enhance public transport.",
  "which": "Based on priority scoring, these locations need **immediate inspection**:\n\n🔴 **Ghaziabad - Indirapuram** (AQI: 335)\n- 10 construction sites operating without permits\n- Industrial zone emissions 28% above limits\n\n🔴 **Delhi - Anand Vihar** (AQI: 312)\n- Traffic congestion at 4 major intersections\n- Nearby waste burning detected\n\n🟠 **Kanpur - Fazalganj** (AQI: 278)\n- 3 factories exceeding SO2 emission norms\n- Lack of green buffer zones",
  "what": "The pollution spike in Ghaziabad (AQI: 335) is caused by:\n\n📊 **Source Attribution Analysis**:\n- Traffic: 30% — NH-24 congestion, diesel trucks\n- Industry: 28% — Unauthorized factories in Sahibabad\n- Construction: 22% — Metro expansion + commercial projects\n- Crop Burning: 10% — Windborne from Western UP\n- Other: 10% — Dust resuspension, waste burning\n\n🌡️ **Meteorological Factors**: Low wind (4 km/h), high temperature (39°C), no rainfall predicted for 5 days.\n\n⚡ **AI Confidence**: 90% based on satellite, sensor, and meteorological data fusion.",
  "how": "Here are evidence-based strategies for UP authorities:\n\n**Immediate (0-48 hours)**:\n1. Deploy fog cannons in Ghaziabad, Lucknow, Kanpur\n2. Enforce odd-even vehicle scheme\n3. Halt all non-essential construction\n4. Shut down brick kilns in 50km radius\n\n**Short-term (1-4 weeks)**:\n1. Install smog towers at 5 critical junctions\n2. Launch electric bus fleet on high-traffic routes\n3. Mandate dust screens on all construction sites\n\n**Long-term (3-12 months)**:\n1. Transition 500 industries to cleaner fuels\n2. Plant 1M trees along highways\n3. Create 10 urban forests in each city",
};

// ===== AQI Ticker Data =====
export const tickerData = [
  { city: "Delhi", aqi: 312 },
  { city: "Mumbai", aqi: 142 },
  { city: "Bangalore", aqi: 78 },
  { city: "Kolkata", aqi: 198 },
  { city: "Chennai", aqi: 95 },
  { city: "Hyderabad", aqi: 68 },
  { city: "Ghaziabad", aqi: 335 },
  { city: "Lucknow", aqi: 245 },
  { city: "Kanpur", aqi: 278 },
  { city: "Patna", aqi: 220 },
  { city: "Jaipur", aqi: 155 },
  { city: "Pune", aqi: 82 },
];
