"""
API route: POST /advisory

Accepts a `DecisionOutput` (typically produced by `POST /decision`) and
returns an `AdvisoryResponse` generated by the LLM Advisory Agent
(Agent 2), containing both an authority recommendation and a citizen
advisory.
"""

import logging
from functools import lru_cache

from fastapi import APIRouter, Depends, HTTPException, status

from app.schemas.advisory_schema import AdvisoryResponse
from app.schemas.decision_schema import DecisionOutput
from app.services.agents.llm_advisory_agent import LLMAdvisoryAgentError
from app.services.orchestration.decision_workflow import DecisionWorkflow

logger = logging.getLogger(__name__)

router = APIRouter(prefix="/advisory", tags=["LLM Advisory"])


@lru_cache
def get_decision_workflow() -> DecisionWorkflow:
    """FastAPI dependency provider for a shared `DecisionWorkflow` instance.

    Shares the same underlying `DecisionWorkflow`/`LLMAdvisoryAgent`/`GroqClient`
    singletons as `app.api.decision` via `lru_cache`, avoiding redundant
    client/connection setup.
    """
    return DecisionWorkflow()


@router.post(
    "",
    response_model=AdvisoryResponse,
    status_code=status.HTTP_200_OK,
    summary="Generate authority and citizen advisories from a computed decision",
)
async def create_advisory(
    decision: DecisionOutput,
    language: str = "English",
    workflow: DecisionWorkflow = Depends(get_decision_workflow),
) -> AdvisoryResponse:
    """Generate authority + citizen advisories for a given decision.

    Args:
        decision: The decision payload (output of `POST /decision`).
        language: Optional language target for citizen advisory.
        workflow: Injected orchestration workflow.

    Returns:
        The `AdvisoryResponse` generated by the LLM Advisory Agent.

    Raises:
        HTTPException: 502 if the upstream LLM (Groq) call fails,
            500 for any other unexpected failure.
    """
    try:
        # Wrap execution in Parent Guardrails
        from app.services.guardrails import ParentGuardrails
        
        async def _run():
            return await workflow._advisory_agent.generate_advisory(decision, language=language)

        result_model = await _run()
        result_dict = result_model.model_dump()
        
        # Apply output guardrail checks
        final_result = ParentGuardrails.run_safe(
            agent_name="Agent 8 - LLM Advisory Agent",
            agent_fn=lambda: result_dict,
            confidence_threshold=0.70
        )
        return AdvisoryResponse(**final_result)
        
    except LLMAdvisoryAgentError as exc:
        logger.error("LLM Advisory Agent failed: %s", exc)
        raise HTTPException(
            status_code=status.HTTP_502_BAD_GATEWAY,
            detail="Failed to generate advisory from the LLM provider.",
        ) from exc
    except Exception as exc:  # noqa: BLE001 - convert any internal failure to a clean 500
        logger.exception("Unexpected error while generating advisory")
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail="Unexpected error while generating advisory.",
        ) from exc
